# Generated by Django 5.2.5 on 2025-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Português'), ('historia', 'História'), ('geografia', 'Geografia'), ('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biologia')], max_length=20)),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1)),
                ('texto', models.TextField()),
                ('alternativa_a', models.CharField(max_length=255)),
                ('alternativa_b', models.CharField(max_length=255)),
                ('alternativa_c', models.CharField(max_length=255)),
                ('alternativa_d', models.CharField(max_length=255)),
                ('alternativa_e', models.CharField(max_length=255)),
                ('resposta_correta', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1)),
            ],
        ),
    ]
