# Generated by Django 5.2.5 on 2025-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simula', '0002_simulado_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='tempo_levado',
            field=models.IntegerField(blank=True, help_text='Duração do simulado em segundos', null=True),
        ),
    ]
