# Generated by Django 5.2.5 on 2025-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simula', '0003_simulado_tempo_levado'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='questoes_imagens/'),
        ),
    ]
