# Generated by Django 5.2.5 on 2025-08-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simula', '0004_questao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='tipo',
            field=models.CharField(choices=[('PERSONALIZADO', 'Personalizado'), ('ENEM', 'ENEM')], default='PERSONALIZADO', max_length=15),
        ),
    ]
