# Generated by Django 5.2.5 on 2025-08-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simula', '0005_simulado_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='imagem',
        ),
    ]
