# Generated by Django 5.2.5 on 2025-08-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simula', '0006_remover_campo_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name_plural': 'Questoes'},
        ),
    ]
